MESSAGE(STATUS "Building for macOS")

SET(MACOS 1)

IF (CMAKE_SYSTEM_PROCESSOR STREQUAL "arm64" OR CMAKE_OSX_ARCHITECTURES MATCHES "arm64")
    MESSAGE(STATUS "Building for Apple silicon")
    SET(EMBREE_ARM ON)
#    SET(EMBREE_NEON_AVX2_EMULATION ON)
    OPTION(EMBREE_NEON_AVX2_EMULATION "Enables NEON AVX2 emulation." ON)
ENDIF()

