# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_7Z "")
SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_IFW "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TXZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Visual Studio 10 2010")
SET(CPACK_COMPONENTS_ALL "lib;devel;examples")
SET(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
SET(CPACK_COMPONENT_DEVEL_DEPENDS "lib")
SET(CPACK_COMPONENT_DEVEL_DESCRIPTION "Header Files for C and ISPC required to develop applications with Embree.")
SET(CPACK_COMPONENT_DEVEL_DISPLAY_NAME "Development")
SET(CPACK_COMPONENT_EXAMPLES_DEPENDS "lib")
SET(CPACK_COMPONENT_EXAMPLES_DESCRIPTION "Tutorials demonstrating how to use Embree.")
SET(CPACK_COMPONENT_EXAMPLES_DISPLAY_NAME "Examples")
SET(CPACK_COMPONENT_EXAMPLES_XEONPHI_DEPENDS "lib_xeonphi")
SET(CPACK_COMPONENT_EXAMPLES_XEONPHI_DESCRIPTION "Tutorials demonstrating how to use Embree.
For The Intel Xeon Phi coprocessor.")
SET(CPACK_COMPONENT_EXAMPLES_XEONPHI_NAME "Xeon Phi Examples")
SET(CPACK_COMPONENT_LIB_DESCRIPTION "The Embree library including documentation.")
SET(CPACK_COMPONENT_LIB_DISPLAY_NAME "Library")
SET(CPACK_COMPONENT_LIB_REQUIRED "ON")
SET(CPACK_COMPONENT_LIB_XEONPHI_DEPENDS "lib")
SET(CPACK_COMPONENT_LIB_XEONPHI_DESCRIPTION "The Embree library including documentation.
For The Intel Xeon Phi coprocessor.")
SET(CPACK_COMPONENT_LIB_XEONPHI_NAME "Xeon Phi Library")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "NSIS")
SET(CPACK_INSTALL_CMAKE_PROJECTS "D:/info/embree/0embree-2.10.0/embree-2.10.0;embree2;ALL;/")
SET(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/embree2")
SET(CPACK_MODULE_PATH "D:/info/embree/0embree-2.10.0/embree-2.10.0/common/cmake")
SET(CPACK_NSIS_CONTACT "embree_support@intel.com")
SET(CPACK_NSIS_DISPLAY_NAME "Embree v2.10.0 win32")
SET(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES\\Intel")
SET(CPACK_NSIS_MENU_LINKS "share/doc/embree2/LICENSE.txt;LICENSE;share/doc/embree2/CHANGELOG.txt;CHANGELOG;share/doc/embree2/README.md;README.md;share/doc/embree2/readme.pdf;readme.pdf;bin/triangle_geometry;triangle_geometry;bin/dynamic_scene;dynamic_scene;bin/user_geometry;user_geometry;bin/viewer;viewer;bin/instanced_geometry;instanced_geometry;bin/intersection_filter;intersection_filter;bin/pathtracer;pathtracer;bin/hair_geometry;hair_geometry;bin/subdivision_geometry;subdivision_geometry;bin/displacement_geometry;displacement_geometry;bin/bvh_builder;bvh_builder;bin/lazy_geometry;lazy_geometry;bin/motion_blur_geometry;motion_blur_geometry;bin/interpolation;interpolation;bin/curve_geometry;curve_geometry;bin/viewer_stream;viewer_stream;bin/verify;verify;bin/benchmark;benchmark;bin/retrace;retrace")
SET(CPACK_NSIS_MUI_ICON "D:/info/embree/0embree-2.10.0/embree-2.10.0/scripts/install_windows/icon32.ico")
SET(CPACK_NSIS_PACKAGE_NAME "Embree v2.10.0 win32")
SET(CPACK_NSIS_URL_INFO_ABOUT "http://embree.github.io/")
SET(CPACK_OUTPUT_CONFIG_FILE "D:/info/embree/0embree-2.10.0/embree-2.10.0/CPackConfig.cmake")
SET(CPACK_PACKAGE_CONTACT "embree_support@intel.com")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "d:/inst/cmake-3.5.0-rc1-win32-x86/cmake-3.5.0-rc1-win32-x86/share/cmake-3.5/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Embree: High Performance Ray Tracing Kernels")
SET(CPACK_PACKAGE_FILE_NAME "embree-2.10.0.win32")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "Embree v2.10.0 win32")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Embree v2.10.0 win32")
SET(CPACK_PACKAGE_NAME "Embree Win32")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "Intel Corporation")
SET(CPACK_PACKAGE_VERSION "2.10.0")
SET(CPACK_PACKAGE_VERSION_MAJOR "2")
SET(CPACK_PACKAGE_VERSION_MINOR "10")
SET(CPACK_PACKAGE_VERSION_PATCH "0")
SET(CPACK_RESOURCE_FILE_LICENSE "D:/info/embree/0embree-2.10.0/embree-2.10.0/LICENSE.txt")
SET(CPACK_RESOURCE_FILE_README "D:/info/embree/0embree-2.10.0/embree-2.10.0/README.md")
SET(CPACK_RESOURCE_FILE_WELCOME "d:/inst/cmake-3.5.0-rc1-win32-x86/cmake-3.5.0-rc1-win32-x86/share/cmake-3.5/Templates/CPack.GenericWelcome.txt")
SET(CPACK_RPM_PACKAGE_RELEASE "1")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_7Z "ON")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "7Z;ZIP")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "D:/info/embree/0embree-2.10.0/embree-2.10.0/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TXZ "")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "ON")
SET(CPACK_SYSTEM_NAME "win32")
SET(CPACK_TOPLEVEL_TAG "win32")
SET(CPACK_WIX_SIZEOF_VOID_P "4")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "D:/info/embree/0embree-2.10.0/embree-2.10.0/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
