## Copyright 2009-2021 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

SET(PACKAGE_VERSION @EMBREE_VERSION@)

IF (${PACKAGE_FIND_VERSION_MAJOR} EQUAL @EMBREE_VERSION_MAJOR@)
  IF (${PACKAGE_FIND_VERSION} VERSION_LESS @EMBREE_VERSION@)
    SET(PACKAGE_VERSION_COMPATIBLE 1)  
  ENDIF()
  IF (${PACKAGE_FIND_VERSION} VERSION_EQUAL @EMBREE_VERSION@)
    SET(PACKAGE_VERSION_EXACT 1)  
  ENDIF()
ELSE()
  SET(PACKAGE_VERSION_UNSUITABLE 1)
ENDIF()
