print("AOEUAOEUAOEUAOEUAOEU")
print("AOEUAOEUAOEUAOEUAOEU")
print("AOEUAOEUAOEUAOEUAOEU")
print("AOEUAOEUAOEUAOEUAOEU")
print("AOEUAOEUAOEUAOEUAOEU")
print("AOEUAOEUAOEUAOEUAOEU")
print("AOEUAOEUAOEUAOEUAOEU")

from .pyembree import *