## Copyright 2022 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

name: continuous

permissions: read-all

on:
  workflow_dispatch:
  push:

jobs:
  ################################################################################
  ################################################################################
  # GPU tests
  ################################################################################
  ###############################################################################

  ########################################
  # Linux DG2
  ########################################

  linux-GPU-JIT-build:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/ubuntu:24.04
      runs-on: '[ "Linux", "docker", "build" ]'
      env-from-files: ./.github/workflows/dpcpp-sycl-nightly.env
      artifact-out: linux-GPU-JIT-build
      artifact-path: ./build/*.tar.gz
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=Release"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_TESTING_INTENSITY=3"
        opts+=" -DEMBREE_SYCL_SUPPORT=ON"
        opts+=" -DEMBREE_SYCL_AOT_DEVICES=none"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DEMBREE_ZIP_MODE=ON"
        opts+=" -DCMAKE_C_COMPILER=clang"
        opts+=" -DCMAKE_CXX_COMPILER=clang++"

        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config Release
        cmake --build build/embree/build --config Release --target build
        cp build/embree/build/embree-*.tar.gz build/

  linux-DG2-JIT-PUBLIC-test:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: ["linux-GPU-JIT-build"]
    with:
      image: embree/ubuntu:24.04
      options: --device=/dev/dri:/dev/dri
      runs-on: '[ "Linux", "docker", "dg2" ]'
      env-from-files: ./.github/workflows/dpcpp-sycl-nightly.env ./.github/workflows/gfx-ubuntu24-public.env
      artifact-in: linux-GPU-JIT-build
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type ctest)
        ./scripts/run-tests.sh --type ctest --embree-dir "$EMBREE_PATH" --ctest-config RelWithDebInfo

  linux-PVC-JIT-PUBLIC-test:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: ["linux-GPU-JIT-build"]
    with:
      image: embree/ubuntu:24.04
      options: --device=/dev/dri:/dev/dri
      runs-on: '[ "Linux", "docker", "pvc" ]'
      env-from-files: ./.github/workflows/dpcpp-sycl-nightly.env ./.github/workflows/gfx-ubuntu24-public.env
      artifact-in: linux-GPU-JIT-build
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type ctest)
        ./scripts/run-tests.sh --type ctest --embree-dir "$EMBREE_PATH" --ctest-config Release

  linux-DG2-JIT-PUBLIC-ICX-build:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/ubuntu:24.04
      runs-on: '[ "Linux", "docker", "build" ]'
      dpcpp-version: intel/2025.2
      artifact-out: linux-DG2-JIT-PUBLIC-ICX-build
      artifact-path: ./build/*.tar.gz
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=Release"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_TESTING_INTENSITY=3"
        opts+=" -DEMBREE_SYCL_SUPPORT=ON"
        opts+=" -DEMBREE_SYCL_AOT_DEVICES=none"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DEMBREE_ZIP_MODE=ON"
        opts+=" -DCMAKE_C_COMPILER=icx"
        opts+=" -DCMAKE_CXX_COMPILER=icpx"

        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config Release
        cmake --build build/embree/build --config Release --target build
        cp build/embree/build/embree-*.tar.gz build/

  linux-DG2-JIT-PUBLIC-ICX-test:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: ["linux-DG2-JIT-PUBLIC-ICX-build"]
    with:
      image: embree/ubuntu:24.04
      options: --device=/dev/dri:/dev/dri
      runs-on: '[ "Linux", "docker", "dg2" ]'
      env-from-files: ./.github/workflows/gfx-ubuntu24-public.env
      dpcpp-version: intel/2025.2
      artifact-in: linux-DG2-JIT-PUBLIC-ICX-build
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type ctest)
        ./scripts/run-tests.sh --type ctest --embree-dir "$EMBREE_PATH" --ctest-config Release


  linux-DG2-JIT-PUBLIC-debug-build:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/ubuntu:24.04
      runs-on: '[ "Linux", "docker", "build" ]'
      env-from-files: ./.github/workflows/dpcpp-sycl-nightly.env
      artifact-out: linux-DG2-JIT-PUBLIC-debug-build
      artifact-path: ./build/*.tar.gz
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=Debug"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_TESTING_INTENSITY=3"
        opts+=" -DEMBREE_SYCL_SUPPORT=ON"
        opts+=" -DEMBREE_SYCL_AOT_DEVICES=none"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DEMBREE_ZIP_MODE=ON"

        cmake -S superbuild -B build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config Debug
        cmake --build build/embree/build --config Debug --target build
        cp build/embree/build/embree-*.tar.gz build/

  ########################################
  # Windows DG2
  ########################################

  windows-JIT-build:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    with:
      force-delete: true
      runs-on: '[ "Windows",  "build" ]'
      env-from-files: ./.github/workflows/dpcpp-sycl-nightly.env
      artifact-out: windows-JIT-build
      artifact-path: ./build/*.zip
      cmd: |
        $opts  = "-DCMAKE_BUILD_TYPE=Release"
        $opts += " -DBUILD_TESTING=ON"
        $opts += " -DEMBREE_TUTORIALS=ON"
        $opts += " -DEMBREE_ISPC_SUPPORT=ON"
        $opts += " -DEMBREE_TESTING_INTENSITY=3"
        $opts += " -DEMBREE_SYCL_SUPPORT=ON"
        $opts += " -DEMBREE_SYCL_AOT_DEVICES=none"
        $opts += " -DEMBREE_MAX_ISA=AVX512"
        $opts += " -DEMBREE_INSTALL_DEPENDENCIES=ON"
        $opts += " -DEMBREE_TESTING_INSTALL_TESTS=ON"
        $opts += " -DCMAKE_INSTALL_TESTDIR=testing"
        $opts += " -DEMBREE_ZIP_MODE=ON"
        $opts += " -DCMAKE_C_COMPILER=clang"
        $opts += " -DCMAKE_CXX_COMPILER=clang++"

        cmake -S superbuild -B build -G Ninja -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config Release
        cmake --build build/embree/build --config Release --target build
        Copy-Item build/embree/build/embree-*.zip build/ -Force

  windows-DG2-JIT-test:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    needs: ["windows-JIT-build"]
    with:
      runs-on: '[ "Windows", "dg2" ]'
      env-from-files: ./.github/workflows/dpcpp-sycl-nightly.env ./.github/workflows/gfx-windows-public.env
      artifact-in: windows-JIT-build
      cmd: |
        $EmbreeDir = .\\scripts\\prepare-test-files.ps1 -TestType ctest
        .\\scripts\\run-tests.ps1 -TestType ctest -EmbreeDir $EmbreeDir -CtestConfig Release

  windows-BMG-JIT-test:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    needs: ["windows-JIT-build"]
    with:
      runs-on: '[ "Windows", "bmg" ]'
      env-from-files: ./.github/workflows/dpcpp-sycl-nightly.env ./.github/workflows/gfx-windows-public.env
      artifact-in: windows-JIT-build
      cmd: |
        $EmbreeDir = .\\scripts\\prepare-test-files.ps1 -TestType ctest
        .\\scripts\\run-tests.ps1 -TestType ctest -EmbreeDir $EmbreeDir -CtestConfig Release

  windows-LNL-JIT-test:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    needs: ["windows-JIT-build"]
    with:
      runs-on: '[ "Windows", "lnl" ]'
      env-from-files: ./.github/workflows/dpcpp-sycl-nightly.env ./.github/workflows/gfx-windows-public.env
      artifact-in: windows-JIT-build
      cmd: |
        $EmbreeDir = .\\scripts\\prepare-test-files.ps1 -TestType ctest
        .\\scripts\\run-tests.ps1 -TestType ctest -EmbreeDir $EmbreeDir -CtestConfig Release

  windows-DG2-JIT-INTERNAL-test:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    needs: ["windows-JIT-build"]
    with:
      runs-on: '[ "Windows",  "dg2" ]'
      env-from-files: ./.github/workflows/dpcpp-sycl-nightly.env ./.github/workflows/gfx-windows-internal.env
      artifact-in: windows-JIT-build
      cmd: |
        $EmbreeDir = .\\scripts\\prepare-test-files.ps1 -TestType ctest
        .\\scripts\\run-tests.ps1 -TestType ctest -EmbreeDir $EmbreeDir -CtestConfig Release

  windows-DG2-JIT-ICX-build:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    with:
      runs-on: '[ "Windows",  "build" ]'
      dpcpp-version: intel/2025.2
      artifact-out: windows-DG2-JIT-ICX-build
      artifact-path: ./build/*.zip
      cmd: |
        $opts  = "-DCMAKE_BUILD_TYPE=Release"
        $opts += " -DBUILD_TESTING=ON"
        $opts += " -DEMBREE_TUTORIALS=ON"
        $opts += " -DEMBREE_ISPC_SUPPORT=ON"
        $opts += " -DEMBREE_TESTING_INTENSITY=3"
        $opts += " -DEMBREE_SYCL_SUPPORT=ON"
        $opts += " -DEMBREE_SYCL_AOT_DEVICES=none"
        $opts += " -DEMBREE_MAX_ISA=AVX512"
        $opts += " -DEMBREE_INSTALL_DEPENDENCIES=ON"
        $opts += " -DEMBREE_TESTING_INSTALL_TESTS=ON"
        $opts += " -DCMAKE_INSTALL_TESTDIR=testing"
        $opts += " -DEMBREE_ZIP_MODE=ON"
        $opts += " -DCMAKE_C_COMPILER=icx"
        $opts += " -DCMAKE_CXX_COMPILER=icx"

        cmake -S superbuild -B build -G Ninja -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config Release
        cmake --build build/embree/build --config Release --target build
        Copy-Item build/embree/build/embree-*.zip build/ -Force

  windows-DG2-JIT-debug-build:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    with:
      force-delete: true
      runs-on: '[ "Windows",  "build" ]'
      env-from-files: ./.github/workflows/dpcpp-sycl-nightly.env
      cmd: |
        $opts  = "-DCMAKE_BUILD_TYPE=Debug"
        $opts += " -DBUILD_TESTING=ON"
        $opts += " -DEMBREE_TUTORIALS=ON"
        $opts += " -DEMBREE_ISPC_SUPPORT=ON"
        $opts += " -DEMBREE_TESTING_INTENSITY=3"
        $opts += " -DEMBREE_SYCL_SUPPORT=ON"
        $opts += " -DEMBREE_SYCL_AOT_DEVICES=none"
        $opts += " -DEMBREE_MAX_ISA=AVX512"
        $opts += " -DEMBREE_INSTALL_DEPENDENCIES=ON"
        $opts += " -DEMBREE_TESTING_INSTALL_TESTS=ON"
        $opts += " -DCMAKE_INSTALL_TESTDIR=testing"
        $opts += " -DEMBREE_ZIP_MODE=ON"

        cmake -S superbuild -B build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -D EMBREE_EXTRA_OPTIONS="$opts"
        # Reduce parallelism for debug build to avoid OOM issues on CI machines with limited resources
        cmake --build build --config Debug --parallel 4
        cmake --build build/embree/build --config Debug --target build --parallel 4

#   ################################################################################
#   ################################################################################
#   # CPU tests
#   ################################################################################
#   ################################################################################

#   ########################################
#   # Linux
#   ########################################

  linux-fedora42-CLANG:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/fedora:42
      runs-on: '[ "Linux", "docker", "avx512" ]'
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=RelWithDebInfo"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_TESTING_INTENSITY=2"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DEMBREE_ZIP_MODE=ON"
        opts+=" -DCMAKE_C_COMPILER=clang"
        opts+=" -DCMAKE_CXX_COMPILER=clang++"

        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config RelWithDebInfo
        cmake --build build/embree/build --config RelWithDebInfo --target build
        cp build/embree/build/embree-*.tar.gz build/

        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type ctest)
        ./scripts/run-tests.sh --type ctest --embree-dir "$EMBREE_PATH" --ctest-config RelWithDebInfo

  linux-fedora42-CLANG-INT-ADDRSANITIZER:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/fedora:42
      runs-on: '[ "Linux", "docker", "build" ]'
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=RelWithDebInfo"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_TESTING_INTENSITY=1"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DEMBREE_TASKING_SYSTEM=INTERNAL"
        opts+=" -DEMBREE_ZIP_MODE=ON"
        opts+=" -DCMAKE_C_COMPILER=clang"
        opts+=" -DCMAKE_CXX_COMPILER=clang++"
        opts+=" -DEMBREE_ADDRESS_SANITIZER=ON"

        cmake -S superbuild -B build -D BUILD_TBB=OFF -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config RelWithDebInfo
        cmake --build build/embree/build --config RelWithDebInfo --target build
        cp build/embree/build/embree-*.tar.gz build/

        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type ctest)
        ./scripts/run-tests.sh --type ctest --embree-dir "$EMBREE_PATH" --ctest-config RelWithDebInfo

  linux-fedora42-ICX:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/fedora:42
      runs-on: '[ "Linux", "docker", "avx512" ]'
      dpcpp-version: intel/2025.2
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=RelWithDebInfo"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_TESTING_INTENSITY=2"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DEMBREE_ZIP_MODE=ON"
        opts+=" -DCMAKE_C_COMPILER=icx"
        opts+=" -DCMAKE_CXX_COMPILER=icpx"

        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config RelWithDebInfo
        cmake --build build/embree/build --config RelWithDebInfo --target build
        cp build/embree/build/embree-*.tar.gz build/

        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type ctest)
        ./scripts/run-tests.sh --type ctest --embree-dir "$EMBREE_PATH" --ctest-config RelWithDebInfo

  linux-ubuntu24_04-GCC:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/ubuntu:24.04
      runs-on: '[ "Linux", "docker", "avx512" ]'
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=Release"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_TESTING_INTENSITY=3"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DEMBREE_ZIP_MODE=ON"

        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config Release
        cmake --build build/embree/build --config Release --target build
        cp build/embree/build/embree-*.tar.gz build/

        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type ctest)
        ./scripts/run-tests.sh --type ctest --embree-dir "$EMBREE_PATH" --ctest-config Release

  linux-ubuntu24_04-ICX:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/ubuntu:24.04
      runs-on: '[ "Linux", "docker", "avx512" ]'
      dpcpp-version: intel/2025.2
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=RelWithDebInfo"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_TESTING_INTENSITY=2"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DEMBREE_ZIP_MODE=ON"
        opts+=" -DCMAKE_C_COMPILER=icx"
        opts+=" -DCMAKE_CXX_COMPILER=icpx"

        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config RelWithDebInfo
        cmake --build build/embree/build --config RelWithDebInfo --target build
        cp build/embree/build/embree-*.tar.gz build/

        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type ctest)
        ./scripts/run-tests.sh --type ctest --embree-dir "$EMBREE_PATH" --ctest-config RelWithDebInfo

  ########################################
  # Windows
  ########################################
  windows-V142:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    with:
      force-delete: true
      runs-on: '[ "Windows",  "build" ]'
      msvc-version: 2019
      cmd: |
        $opts  = "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
        $opts += " -DBUILD_TESTING=ON"
        $opts += " -DEMBREE_TUTORIALS=ON"
        $opts += " -DEMBREE_ISPC_SUPPORT=ON"
        $opts += " -DEMBREE_MAX_INSTANCE_LEVEL_COUNT=8"
        $opts += " -DEMBREE_MAX_ISA=SSE2"
        $opts += " -DEMBREE_INSTALL_DEPENDENCIES=ON"
        $opts += " -DEMBREE_TESTING_INSTALL_TESTS=ON"
        $opts += " -DCMAKE_INSTALL_TESTDIR=testing"
        $opts += " -DEMBREE_ZIP_MODE=ON"

        cmake -S superbuild -B build -G Ninja -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config RelWithDebInfo
        cmake --build build/embree/build --config RelWithDebInfo --target build
        Copy-Item build/embree/build/embree-*.zip build/ -Force

        $EmbreeDir = .\\scripts\\prepare-test-files.ps1 -TestType ctest
        .\\scripts\\run-tests.ps1 -TestType ctest -EmbreeDir $EmbreeDir -CtestConfig RelWithDebInfo

  ########################################
  # MacOS
  ########################################

  macosx-ARM-CLANG-NEON-AVX2:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/macos.yml@main
    with:
      runs-on: '[ "macOS", "build", "arm" ]'
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=RelWithDebInfo"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_TESTING_INTENSITY=2"
        opts+=" -DCMAKE_CXX_COMPILER=clang++"
        opts+=" -DCMAKE_C_COMPILER=clang"
        opts+=" -DCMAKE_INSTALL_BINDIR=bin"
        opts+=" -DCMAKE_INSTALL_DOCDIR=doc"
        opts+=" -DCMAKE_INSTALL_INCLUDEDIR=include"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DCMAKE_MACOSX_RPATH=ON"
        opts+=" -DCMAKE_SKIP_INSTALL_RPATH=OFF"
        opts+=" -DEMBREE_BUILD_GLFW_FROM_SOURCE=ON"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_MAX_ISA=NEON2X"
        opts+=" -DEMBREE_PATCH_GLFW_SOURCE=ON"
        opts+=" -DEMBREE_TASKING_SYSTEM=TBB"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DEMBREE_ZIP_MODE=ON"

        cmake -S superbuild -B build -D BUILD_TBB_FROM_SOURCE=ON -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config RelWithDebInfo
        cmake --build build/embree/build --config RelWithDebInfo --target build
        cp build/embree/build/embree-*.zip build/

        EMBREE_PATH=$(./scripts/prepare-test-files-macos.sh --type ctest)
        ./scripts/run-tests.sh --type ctest --embree-dir "$EMBREE_PATH" --ctest-config RelWithDebInfo

  macosx-ARM-CLANG-NEON:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/macos.yml@main
    with:
      runs-on: '[ "macOS", "build", "arm" ]'
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=RelWithDebInfo"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_TESTING_INTENSITY=2"
        opts+=" -DCMAKE_CXX_COMPILER=clang++"
        opts+=" -DCMAKE_C_COMPILER=clang"
        opts+=" -DCMAKE_INSTALL_BINDIR=bin"
        opts+=" -DCMAKE_INSTALL_DOCDIR=doc"
        opts+=" -DCMAKE_INSTALL_INCLUDEDIR=include"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DCMAKE_MACOSX_RPATH=ON"
        opts+=" -DCMAKE_SKIP_INSTALL_RPATH=OFF"
        opts+=" -DEMBREE_BUILD_GLFW_FROM_SOURCE=ON"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_MAX_ISA=NEON"
        opts+=" -DEMBREE_PATCH_GLFW_SOURCE=ON"
        opts+=" -DEMBREE_TASKING_SYSTEM=TBB"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DEMBREE_ZIP_MODE=ON"

        cmake -S superbuild -B build -D BUILD_TBB_FROM_SOURCE=ON -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config RelWithDebInfo
        cmake --build build/embree/build --config RelWithDebInfo --target build
        cp build/embree/build/embree-*.zip build/

        EMBREE_PATH=$(./scripts/prepare-test-files-macos.sh --type ctest)
        ./scripts/run-tests.sh --type ctest --embree-dir "$EMBREE_PATH" --ctest-config RelWithDebInfo

  macosx-x64-CLANG:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/macos.yml@main
    with:
      runs-on: '[ "macOS", "build", "x86_64" ]'
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=RelWithDebInfo"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_TESTING_INTENSITY=2"
        opts+=" -DCMAKE_CXX_COMPILER=clang++"
        opts+=" -DCMAKE_C_COMPILER=clang"
        opts+=" -DCMAKE_INSTALL_BINDIR=bin"
        opts+=" -DCMAKE_INSTALL_DOCDIR=doc"
        opts+=" -DCMAKE_INSTALL_INCLUDEDIR=include"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DCMAKE_MACOSX_RPATH=ON"
        opts+=" -DCMAKE_SKIP_INSTALL_RPATH=OFF"
        opts+=" -DEMBREE_BUILD_GLFW_FROM_SOURCE=ON"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DEMBREE_PATCH_GLFW_SOURCE=ON"
        opts+=" -DEMBREE_TASKING_SYSTEM=TBB"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DEMBREE_ZIP_MODE=ON"

        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config RelWithDebInfo
        cmake --build build/embree/build --config RelWithDebInfo --target build
        cp build/embree/build/embree-*.zip build/

        EMBREE_PATH=$(./scripts/prepare-test-files-macos.sh --type ctest)
        ./scripts/run-tests.sh --type ctest --embree-dir "$EMBREE_PATH" --ctest-config RelWithDebInfo

  macosx-ARM-CLANG-NEON-AVX2-universal-binaries:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/macos.yml@main
    with:
      runs-on: '[ "macOS", "build", "arm" ]'
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=RelWithDebInfo"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=OFF"
        opts+=" -DEMBREE_TESTING_INTENSITY=2"
        opts+=" -DCMAKE_CXX_COMPILER=clang++"
        opts+=" -DCMAKE_C_COMPILER=clang"
        opts+=" -DCMAKE_INSTALL_BINDIR=bin"
        opts+=" -DCMAKE_INSTALL_DOCDIR=doc"
        opts+=" -DCMAKE_INSTALL_INCLUDEDIR=include"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DCMAKE_MACOSX_RPATH=ON"
        opts+=" -DCMAKE_SKIP_INSTALL_RPATH=OFF"
        opts+=" -DEMBREE_BUILD_GLFW_FROM_SOURCE=ON"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_MAX_ISA=NEON2X"
        opts+=" -DEMBREE_PATCH_GLFW_SOURCE=ON"
        opts+=" -DEMBREE_TASKING_SYSTEM=TBB"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DEMBREE_ZIP_MODE=ON"
        opts+=" -DCMAKE_OSX_ARCHITECTURES=arm64;x86_64"

        cmake -S superbuild -B build -D BUILD_TBB_FROM_SOURCE=ON -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config RelWithDebInfo
        cmake --build build/embree/build --config RelWithDebInfo --target build
        cp build/embree/build/embree-*.zip build/

        EMBREE_PATH=$(./scripts/prepare-test-files-macos.sh --type ctest)
        ./scripts/run-tests.sh --type ctest --embree-dir "$EMBREE_PATH" --ctest-config RelWithDebInfo

  ########################################
  # Static code analysis jobs
  ########################################

  static-analysis-lin:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/static_analysis.yml@main
    with:
      os: Linux
      project: Embree
      prebuild: |
        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="-DCMAKE_BUILD_TYPE=Release -DEMBREE_MAX_ISA=SSE2"
      build: |
        cmake --build build --config Release
