## Copyright 2022 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

name: integrate

permissions: read-all

on:
  schedule:
    - cron:  '01 00 * * *'
  workflow_dispatch:

jobs:

####################################################################
# Linux
####################################################################
  integrate-linux-GCC:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      artifact-out: integrate-linux-GCC
      artifact-path: ./build/*.tar.gz
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=Release"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DEMBREE_ZIP_MODE=ON"

        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config Release
        cmake --build build/embree/build --config Release --target build
        cp build/embree/build/embree-*.tar.gz build/

  integrate-linux-GCC-test-GCC:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-linux-GCC" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      artifact-in: integrate-linux-GCC
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH"

  integrate-linux-GCC-test-CLANG:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-linux-GCC" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      artifact-in: integrate-linux-GCC
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH" --c-compiler clang --cxx-compiler clang++

  integrate-linux-GCC-test-ICX:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-linux-GCC" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      dpcpp-version: intel/2025.2
      artifact-in: integrate-linux-GCC
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH" --c-compiler icx --cxx-compiler icpx

  integrate-linux-ICX:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      dpcpp-version: intel/2025.2
      artifact-out: integrate-linux-ICX
      artifact-path: ./build/*.tar.gz
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=Release"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DEMBREE_ZIP_MODE=ON"
        opts+=" -DCMAKE_C_COMPILER=icx"
        opts+=" -DCMAKE_CXX_COMPILER=icpx"

        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config Release
        cmake --build build/embree/build --config Release --target build
        cp build/embree/build/embree-*.tar.gz build/

  integrate-linux-ICX-test-GCC:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-linux-ICX" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      artifact-in: integrate-linux-ICX
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH"

  integrate-linux-ICX-test-CLANG:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-linux-ICX" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      dpcpp-version: intel/2025.2
      artifact-in: integrate-linux-ICX
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH" --c-compiler clang --cxx-compiler clang++

  integrate-linux-ICX-test-ICX:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-linux-ICX" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      dpcpp-version: intel/2025.2
      artifact-in: integrate-linux-ICX
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH" --c-compiler icx --cxx-compiler icpx
        
  integrate-static-linux-CLANG:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      artifact-out: integrate-static-linux-CLANG
      artifact-path: ./build/*.tar.gz
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=Release"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DEMBREE_ZIP_MODE=ON"
        opts+=" -DCMAKE_C_COMPILER=clang"
        opts+=" -DCMAKE_CXX_COMPILER=clang++"

        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config Release
        cmake --build build/embree/build --config Release --target build
        cp build/embree/build/embree-*.tar.gz build/

  integrate-static-linux-CLANG-test-GCC:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-static-linux-CLANG" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      artifact-in: integrate-static-linux-CLANG
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH"

  integrate-static-linux-CLANG-test-CLANG:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-static-linux-CLANG" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      artifact-in: integrate-static-linux-CLANG
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH" --c-compiler clang --cxx-compiler clang++

  integrate-static-linux-CLANG-test-ICX:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-static-linux-CLANG" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      dpcpp-version: intel/2025.2
      artifact-in: integrate-static-linux-CLANG
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH" --c-compiler icx --cxx-compiler icpx
        


####################################################################
# Linux STATIC
####################################################################
  integrate-static-linux-GCC:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      artifact-out: integrate-static-linux-GCC
      artifact-path: ./build/*.tar.gz
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=Release"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DEMBREE_ZIP_MODE=ON"

        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config Release
        cmake --build build/embree/build --config Release --target build
        cp build/embree/build/embree-*.tar.gz build/

  integrate-static-linux-GCC-test-GCC:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-static-linux-GCC" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      artifact-in: integrate-static-linux-GCC
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH"

  integrate-static-linux-GCC-test-CLANG:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-static-linux-GCC" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      artifact-in: integrate-static-linux-GCC
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH" --c-compiler clang --cxx-compiler clang++

  integrate-static-linux-GCC-test-ICX:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-static-linux-GCC" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      dpcpp-version: intel/2025.2
      artifact-in: integrate-static-linux-GCC
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH" --c-compiler icx --cxx-compiler icpx


  integrate-static-linux-ICX:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      dpcpp-version: intel/2025.2
      artifact-out: integrate-static-linux-ICX
      artifact-path: ./build/*.tar.gz
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=Release"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DEMBREE_ZIP_MODE=ON"
        opts+=" -DCMAKE_C_COMPILER=icx"
        opts+=" -DCMAKE_CXX_COMPILER=icpx"

        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config Release
        cmake --build build/embree/build --config Release --target build
        cp build/embree/build/embree-*.tar.gz build/

  integrate-static-linux-ICX-test-GCC:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-static-linux-ICX" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      dpcpp-version: intel/2025.2
      artifact-in: integrate-static-linux-ICX
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH"

  integrate-static-linux-ICX-test-CLANG:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-static-linux-ICX" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      dpcpp-version: intel/2025.2
      artifact-in: integrate-static-linux-ICX
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH" --c-compiler clang --cxx-compiler clang++

  integrate-static-linux-ICX-test-ICX:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-static-linux-ICX" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      dpcpp-version: intel/2025.2
      artifact-in: integrate-static-linux-ICX
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH" --c-compiler icx --cxx-compiler icpx
        
  integrate-linux-CLANG:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      artifact-out: integrate-linux-CLANG
      artifact-path: ./build/*.tar.gz
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=Release"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DEMBREE_ZIP_MODE=ON"
        opts+=" -DCMAKE_C_COMPILER=clang"
        opts+=" -DCMAKE_CXX_COMPILER=clang++"

        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config Release
        cmake --build build/embree/build --config Release --target build
        cp build/embree/build/embree-*.tar.gz build/

  integrate-linux-CLANG-test-GCC:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-linux-CLANG" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      artifact-in: integrate-linux-CLANG
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH"

  integrate-linux-CLANG-test-CLANG:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-linux-CLANG" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      artifact-in: integrate-linux-CLANG
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH" --c-compiler clang --cxx-compiler clang++

  integrate-linux-CLANG-test-ICX:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-linux-CLANG" ]
    with:
      image: embree/rockylinux:8.7
      runs-on: '[ "Linux", "docker", "avx512" ]'
      dpcpp-version: intel/2025.2
      artifact-in: integrate-linux-CLANG
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        ./scripts/run-tests.sh --type integration --embree-dir "$EMBREE_PATH" --c-compiler icx --cxx-compiler icpx




####################################################################
# Linux SYCL
####################################################################
  integrate-sycl-linux-ICX:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/ubuntu:24.04
      runs-on: '[ "Linux", "docker", "build" ]'
      dpcpp-version: intel/2025.2
      artifact-out: integrate-sycl-linux-ICX
      artifact-path: ./build/*.tar.gz
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=Release"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DEMBREE_SYCL_SUPPORT=ON"
        opts+=" -DEMBREE_SYCL_AOT_DEVICES=none"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DEMBREE_ZIP_MODE=ON"
        opts+=" -DCMAKE_C_COMPILER=icx"
        opts+=" -DCMAKE_CXX_COMPILER=icpx"

        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config Release
        cmake --build build/embree/build --config Release --target build
        cp build/embree/build/embree-*.tar.gz build/

  integrate-sycl-linux-ICX-test:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-sycl-linux-ICX" ]
    with:
      image: embree/ubuntu:24.04
      options: --device=/dev/dri:/dev/dri
      runs-on: '[ "Linux", "docker", "dg2" ]'
      env-from-files: ./.github/workflows/gfx-ubuntu24-public.env
      dpcpp-version: intel/2025.2
      artifact-in: integrate-sycl-linux-ICX
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        cd tests/integration/test_embree_release
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -Dembree_DIR="$EMBREE_PATH"
        cmake --build build --config Release
        ./build/test
        
  integrate-sycl-linux-DPCPP:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/ubuntu:24.04
      runs-on: '[ "Linux", "docker", "build" ]'
      env-from-files: ./.github/workflows/dpcpp-sycl-nightly.env
      artifact-out: integrate-sycl-linux-DPCPP
      artifact-path: ./build/*.tar.gz
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=Release"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_MAX_ISA=SSE2"
        opts+=" -DEMBREE_SYCL_SUPPORT=ON"
        opts+=" -DEMBREE_SYCL_AOT_DEVICES=none"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DEMBREE_ZIP_MODE=ON"
        opts+=" -DCMAKE_C_COMPILER=clang"
        opts+=" -DCMAKE_CXX_COMPILER=clang++"

        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config Release
        cmake --build build/embree/build --config Release --target build
        cp build/embree/build/embree-*.tar.gz build/

  integrate-sycl-linux-DPCPP-test:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: [ "integrate-sycl-linux-DPCPP" ]
    with:
      image: embree/ubuntu:24.04
      options: --device=/dev/dri:/dev/dri
      runs-on: '[ "Linux", "docker", "dg2" ]'
      env-from-files: ./.github/workflows/dpcpp-sycl-nightly.env ./.github/workflows/gfx-ubuntu24-public.env
      artifact-in: integrate-sycl-linux-DPCPP
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files.sh --type integration)
        cd tests/integration/test_embree_release
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -Dembree_DIR="$EMBREE_PATH"
        cmake --build build --config Release
        ./build/test
        




####################################################################
# MacOS
####################################################################
  integrate-macos-GCC:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/macos.yml@main
    with:
      runs-on: '[ "macOS", "build", "x86_64" ]'
      artifact-out: integrate-macos-GCC
      artifact-path: ./build/*.zip
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=Release"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DCMAKE_INSTALL_BINDIR=bin"
        opts+=" -DCMAKE_INSTALL_DOCDIR=doc"
        opts+=" -DCMAKE_INSTALL_INCLUDEDIR=include"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DCMAKE_MACOSX_RPATH=ON"
        opts+=" -DCMAKE_SKIP_INSTALL_RPATH=OFF"
        opts+=" -DEMBREE_BUILD_GLFW_FROM_SOURCE=ON"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_PATCH_GLFW_SOURCE=ON"
        opts+=" -DEMBREE_TASKING_SYSTEM=TBB"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DEMBREE_ZIP_MODE=ON"

        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config Release
        cmake --build build/embree/build --config Release --target build
        cp build/embree/build/embree-*.zip build/

  integrate-macos-GCC-test-GCC:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/macos.yml@main
    needs: [ "integrate-macos-GCC" ]
    with:
      runs-on: '[ "macOS", "build", "x86_64" ]'
      artifact-in: integrate-macos-GCC
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files-macos.sh --type integration)
        cd tests/integration/test_embree_release
        cmake -B build -DCMAKE_BUILD_TYPE=Release -Dembree_DIR="$EMBREE_PATH"
        cmake --build build --config Release
        ./build/test

  integrate-macos-GCC-test-CLANG:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/macos.yml@main
    needs: [ "integrate-macos-GCC" ]
    with:
      runs-on: '[ "macOS", "build", "x86_64" ]'
      artifact-in: integrate-macos-GCC
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files-macos.sh --type integration)
        cd tests/integration/test_embree_release
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -Dembree_DIR="$EMBREE_PATH"
        cmake --build build --config Release
        ./build/test
      
  integrate-macos-CLANG:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/macos.yml@main
    with:
      runs-on: '[ "macOS", "build", "x86_64" ]'
      artifact-out: integrate-macos-CLANG
      artifact-path: ./build/*.zip
      cmd: |
        opts="-DCMAKE_BUILD_TYPE=Release"
        opts+=" -DBUILD_TESTING=ON"
        opts+=" -DEMBREE_TUTORIALS=ON"
        opts+=" -DEMBREE_ISPC_SUPPORT=ON"
        opts+=" -DEMBREE_MAX_ISA=AVX512"
        opts+=" -DCMAKE_CXX_COMPILER=clang++"
        opts+=" -DCMAKE_C_COMPILER=clang"
        opts+=" -DCMAKE_INSTALL_BINDIR=bin"
        opts+=" -DCMAKE_INSTALL_DOCDIR=doc"
        opts+=" -DCMAKE_INSTALL_INCLUDEDIR=include"
        opts+=" -DCMAKE_INSTALL_TESTDIR=testing"
        opts+=" -DCMAKE_MACOSX_RPATH=ON"
        opts+=" -DCMAKE_SKIP_INSTALL_RPATH=OFF"
        opts+=" -DEMBREE_BUILD_GLFW_FROM_SOURCE=ON"
        opts+=" -DEMBREE_INSTALL_DEPENDENCIES=ON"
        opts+=" -DEMBREE_PATCH_GLFW_SOURCE=ON"
        opts+=" -DEMBREE_TASKING_SYSTEM=TBB"
        opts+=" -DEMBREE_TESTING_INSTALL_TESTS=ON"
        opts+=" -DEMBREE_ZIP_MODE=ON"

        cmake -S superbuild -B build -D EMBREE_EXTRA_OPTIONS="$opts"
        cmake --build build --config Release
        cmake --build build/embree/build --config Release --target build
        cp build/embree/build/embree-*.zip build/

  integrate-macos-CLANG-test-GCC:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/macos.yml@main
    needs: [ "integrate-macos-CLANG" ]
    with:
      runs-on: '[ "macOS", "build", "x86_64" ]'
      artifact-in: integrate-macos-CLANG
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files-macos.sh --type integration)
        cd tests/integration/test_embree_release
        cmake -B build -DCMAKE_BUILD_TYPE=Release -Dembree_DIR="$EMBREE_PATH"
        cmake --build build --config Release
        ./build/test

  integrate-macos-CLANG-test-CLANG:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/macos.yml@main
    needs: [ "integrate-macos-CLANG" ]
    with:
      runs-on: '[ "macOS", "build", "x86_64" ]'
      artifact-in: integrate-macos-CLANG
      cmd: |
        EMBREE_PATH=$(./scripts/prepare-test-files-macos.sh --type integration)
        cd tests/integration/test_embree_release
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -Dembree_DIR="$EMBREE_PATH"
        cmake --build build --config Release
        ./build/test
